using DnsServerBlazorApp.Services;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using MudBlazor;
using MudBlazor.Extensions;
using MudBlazor.Services;

namespace DnsServerBlazorApp;

/// <summary>
/// Extension methods that let DnsServerCore embed the Blazor UI
/// inside its own WebApplication without coupling the DNS library
/// directly to MudBlazor or other UI packages.
/// </summary>
public static class BlazorHostingExtensions
{
    /// <summary>
    /// Registers Razor component rendering and all Blazor UI services
    /// (MudBlazor, ThemeService, SessionService, ApiService, HttpClient).
    /// Call this on the <see cref="IServiceCollection"/> before building
    /// the <see cref="Microsoft.AspNetCore.Builder.WebApplication"/>.
    /// </summary>
    public static IServiceCollection AddDnsBlazorServices(this IServiceCollection services)
    {
        services.AddRazorComponents()
                .AddInteractiveServerComponents();

        // HttpClient base address resolved per-request from NavigationManager
        // so it always matches the actual origin the browser is using.
        services.AddScoped(sp => new HttpClient
        {
            BaseAddress = new Uri(
                sp.GetRequiredService<NavigationManager>().BaseUri)
        });

        services.AddMudServices(config =>
        {
            config.SnackbarConfiguration.PositionClass           = Defaults.Classes.Position.TopCenter;
            config.SnackbarConfiguration.PreventDuplicates       = false;
            config.SnackbarConfiguration.NewestOnTop             = true;
            config.SnackbarConfiguration.ShowCloseIcon           = true;
            config.SnackbarConfiguration.VisibleStateDuration    = 5000;
            config.SnackbarConfiguration.HideTransitionDuration  = 300;
            config.SnackbarConfiguration.ShowTransitionDuration  = 300;
            config.SnackbarConfiguration.SnackbarVariant         = Variant.Filled;
        });
        services.AddMudExtensions();

        services.AddScoped<SessionService>();
        services.AddScoped<ApiService>();
        services.AddScoped<ThemeService>();

        return services;
    }

    /// <summary>
    /// Maps <see cref="App"/> as the Blazor root component with interactive
    /// server rendering.  Call this after all API route mappings so that
    /// Blazor acts as the fallback for every non-API request.
    /// </summary>
    public static IEndpointRouteBuilder MapDnsBlazorApp(this IEndpointRouteBuilder endpoints)
    {
        // MapStaticAssets() requires a build-time manifest generated by the SDK.
        // DnsServerApp uses Microsoft.NET.Sdk (not web SDK); StaticWebAssetsEnabled=true
        // in its csproj generates the manifest, but we guard defensively so the app
        // never crashes when the manifest is absent (e.g. pre-build, legacy run).
        var name     = System.Reflection.Assembly.GetEntryAssembly()?.GetName().Name ?? string.Empty;
        var manifest = Path.Combine(AppContext.BaseDirectory, $"{name}.staticwebassets.endpoints.json");
        if (File.Exists(manifest))
            endpoints.MapStaticAssets();

        endpoints.MapRazorComponents<App>()
                 .AddInteractiveServerRenderMode();
        return endpoints;
    }
}
